// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdnL21iMJaVPv5v5aq7MRLhb5SV1r8_M',
    appId: '1:1054716874189:web:6ad043d98c5bf344ba4884',
    messagingSenderId: '1054716874189',
    projectId: 'solutionsrentcar-ecc4f',
    authDomain: 'solutionsrentcar-ecc4f.firebaseapp.com',
    storageBucket: 'solutionsrentcar-ecc4f.firebasestorage.app',
    measurementId: 'G-5D1RKVWP0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5G3JUo-ufPXpvePnlYnRYRZgYbFol9A',
    appId: '1:1054716874189:android:610031771244b1f6ba4884',
    messagingSenderId: '1054716874189',
    projectId: 'solutionsrentcar-ecc4f',
    storageBucket: 'solutionsrentcar-ecc4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49qLEW1hmght5Ypq20c9JIQv7aAt1b9g',
    appId: '1:1054716874189:ios:67ce308ef5459e16ba4884',
    messagingSenderId: '1054716874189',
    projectId: 'solutionsrentcar-ecc4f',
    storageBucket: 'solutionsrentcar-ecc4f.firebasestorage.app',
    iosBundleId: 'com.example.solutionsRentCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC49qLEW1hmght5Ypq20c9JIQv7aAt1b9g',
    appId: '1:1054716874189:ios:67ce308ef5459e16ba4884',
    messagingSenderId: '1054716874189',
    projectId: 'solutionsrentcar-ecc4f',
    storageBucket: 'solutionsrentcar-ecc4f.firebasestorage.app',
    iosBundleId: 'com.example.solutionsRentCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwdnL21iMJaVPv5v5aq7MRLhb5SV1r8_M',
    appId: '1:1054716874189:web:065cb7366a6411dcba4884',
    messagingSenderId: '1054716874189',
    projectId: 'solutionsrentcar-ecc4f',
    authDomain: 'solutionsrentcar-ecc4f.firebaseapp.com',
    storageBucket: 'solutionsrentcar-ecc4f.firebasestorage.app',
    measurementId: 'G-0PZV54853G',
  );

}